"""Speech segment buffer with smart finalization rules based on word count, punctuation, and timeouts."""

from dataclasses import dataclass
import re
import time
from typing import List, Optional

from transcribe.base import TranscriptSegment


@dataclass
class FinalSegment:
    """A finalized speech segment ready for translation and UI display."""

    speaker: Optional[int | str]
    text: str
    start_time: float
    end_time: float
    word_count: int


class SegmentBuffer:
    """Buffers incoming transcript fragments and decides when to finalize a coherent sentence.

    Finalization triggers:
    1. Speaker transition (Speaker A stops, Speaker B starts).
    2. Buffer reaches MAX_WORDS limit.
    3. Buffer reaches MIN_WORDS AND ends with sentence-terminating punctuation (. ? !).
    4. Inactivity timeout (MAX_WAIT_SECONDS elapsed with no new input).
    """

    PUNCTUATION_REGEX = re.compile(r"[.?!…]+$")

    def __init__(
        self,
        min_words: int = 5,
        max_words: int = 25,
        max_wait_seconds: float = 2.5,
    ):
        self.min_words = max(1, min_words)
        self.max_words = max(self.min_words, max_words)
        self.max_wait_seconds = max_wait_seconds

        self._current_speaker: Optional[int | str] = None
        self._buffered_words: List[str] = []
        self._start_time: Optional[float] = None
        self._last_update_time: Optional[float] = None

    @property
    def current_word_count(self) -> int:
        """Number of words currently buffered."""
        return len(self._buffered_words)

    @property
    def has_content(self) -> bool:
        """True if the buffer contains words."""
        return len(self._buffered_words) > 0

    def add_transcript(
        self,
        segment: TranscriptSegment,
        current_time: Optional[float] = None,
    ) -> List[FinalSegment]:
        """Process an incoming transcript segment.

        Returns:
            List[FinalSegment]: Any finalized segments generated by this update.
        """
        now = current_time if current_time is not None else time.time()
        finalized_segments: List[FinalSegment] = []

        raw_text = segment.text.strip()
        if not raw_text:
            return finalized_segments

        incoming_speaker = segment.speaker if segment.speaker is not None else 0

        # Trigger 1: Speaker transition
        if self._buffered_words and incoming_speaker != self._current_speaker:
            flushed = self._finalize_buffer(end_time=segment.start or now)
            if flushed:
                finalized_segments.append(flushed)

        # Set or maintain current speaker
        self._current_speaker = incoming_speaker
        if self._start_time is None:
            self._start_time = segment.start if segment.start > 0 else now
        self._last_update_time = now

        # Add incoming words
        new_words = raw_text.split()
        self._buffered_words.extend(new_words)

        # Trigger 2: Reached MAX_WORDS
        while len(self._buffered_words) >= self.max_words:
            # Slice first max_words
            chunk_words = self._buffered_words[: self.max_words]
            self._buffered_words = self._buffered_words[self.max_words :]

            text = " ".join(chunk_words)
            end_t = segment.end if (not self._buffered_words and segment.end > 0) else now
            finalized_segments.append(
                FinalSegment(
                    speaker=self._current_speaker,
                    text=text,
                    start_time=self._start_time or now,
                    end_time=end_t,
                    word_count=len(chunk_words),
                )
            )
            # Reset start time for remaining words
            self._start_time = now

        # Trigger 3: Reached MIN_WORDS and ends with sentence-ending punctuation
        if len(self._buffered_words) >= self.min_words:
            current_text = " ".join(self._buffered_words)
            if self.PUNCTUATION_REGEX.search(current_text):
                flushed = self._finalize_buffer(end_time=segment.end or now)
                if flushed:
                    finalized_segments.append(flushed)

        return finalized_segments

    def check_timeout(self, current_time: Optional[float] = None) -> Optional[FinalSegment]:
        """Check if silence / lack of updates exceeds MAX_WAIT_SECONDS.

        Returns:
            FinalSegment if timed out and buffer has content, else None.
        """
        if not self._buffered_words or self._last_update_time is None:
            return None

        now = current_time if current_time is not None else time.time()
        elapsed = now - self._last_update_time

        # Trigger 4: Inactivity timeout
        if elapsed >= self.max_wait_seconds:
            return self._finalize_buffer(end_time=now)
        return None

    def flush(self, current_time: Optional[float] = None) -> Optional[FinalSegment]:
        """Force finalize all remaining words in the buffer."""
        now = current_time if current_time is not None else time.time()
        return self._finalize_buffer(end_time=now)

    def _finalize_buffer(self, end_time: float) -> Optional[FinalSegment]:
        """Internal helper to construct FinalSegment and clear state."""
        if not self._buffered_words:
            return None

        text = " ".join(self._buffered_words)
        count = len(self._buffered_words)
        start_t = self._start_time if self._start_time is not None else end_time

        segment = FinalSegment(
            speaker=self._current_speaker,
            text=text,
            start_time=start_t,
            end_time=end_time,
            word_count=count,
        )

        # Clear buffer
        self._buffered_words = []
        self._start_time = None
        self._last_update_time = None
        return segment
